parameters:
- name: DOCKER_REGISTRY_SERVICE_CONNECTION
- name: DOCKER_REGISTRY_URL

jobs:
- job: DockerCI
  pool:
    vmImage: 'ubuntu-latest'
    variables:
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
        DOCKER_PUBLISH: true
    ${{ if ne(variables.IsRelease, 'true') }}:
        DOCKER_IMAGE_TAG_EXT: "-$(Build.SourceVersion)"

  steps:
  - bash: VER=`cat VERSION` && echo '##vso[task.setvariable variable=VER;isOutput=true]'$VER
    name: Version

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: ${{ parameters.DOCKER_REGISTRY_SERVICE_CONNECTION }}

  - bash: scripts/automation/docker-ci.sh
    displayName: 'Docker CI'
    env:
      DOCKER_REGISTRY_URL: ${{ parameters.DOCKER_REGISTRY_URL }}
      DOCKERFILE_PATH: ".devcontainer/Dockerfile"
      DOCKER_IMAGE_NAME: "brightside-dev"
      DOCKER_IMAGE_TAG: $(Version.VER)
