parameters:
- name: DOCKER_IMAGE
- name: DOCKER_REGISTRY_SERVICE_CONNECTION

jobs:
- job: TerraformCI
  pool:
    vmImage: 'ubuntu-latest'
  container:
    image: ${{ parameters.DOCKER_IMAGE }}
    endpoint: ${{ parameters.DOCKER_REGISTRY_SERVICE_CONNECTION }}

  steps:
  - bash: 
    workingDirectory: .
    displayName: 'Check env'

  - bash: terraform init
    workingDirectory: .
    displayName: 'Terraform Init'

  - bash: terraform fmt
    workingDirectory: .
    displayName: 'Terraform Format'

  - bash: terraform validate
    workingDirectory: .
    displayName: 'Terraform Validate'
  
  - bash: ./scripts/automation/terraform-checkvars-ci.sh && terraform plan
    workingDirectory: .
    displayName: 'Terraform Plan'
    env: 
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      TF_VAR_shared_services_virtual_network_resource_group_name: $(SHARED_RESOURCE_GROUP_NAME)
      TF_VAR_shared_services_virtual_network_name: $(SHARED_VNET_NAME)
      TF_VAR_virtual_network_cidr: $(SHARED_VNET_CIDR)
