resources:
  pipelines:
  - pipeline: SharedServices-CI
    source: SharedServices-CI
    trigger:
      branches:
        - master

# TODO: Service connection not currently set via a variable due to this
# unresolved issue: https://github.com/microsoft/azure-pipelines-agent/issues/1307#issuecomment-403194600
variables:
  DOCKER_IMAGE: brightside-dev:latest
  DOCKER_REGISTRY_URL: brdev.azurecr.io

stages:
  - stage: CD
    jobs:

    - job: CD
      pool:
        vmImage: 'ubuntu-latest'
      container:
        image: $(DOCKER_IMAGE)
        endpoint: brightsideACR
      
      steps:
        - checkout: self

        - task: AzureCLI@2
          name: AzCreds
          displayName: Get Azure Credentials
          inputs:
              azureSubscription: brightsideARM-tobe
              scriptType: bash
              addSpnToEnvironment: true
              scriptLocation: inlineScript
              inlineScript: |
                echo '##vso[task.setvariable variable=AZ_SPN;isOutput=true]'$servicePrincipalId
                echo '##vso[task.setvariable variable=AZ_SPN_KEY;isOutput=true]'$servicePrincipalKey
                echo '##vso[task.setvariable variable=AZ_TENANT;isOutput=true]'$tenantId
                AZ_SUB_ID=`az account show -o tsv | awk '{ print $3 }'`
                echo '##vso[task.setvariable variable=AZ_SUB_ID;isOutput=true]'$AZ_SUB_ID

        - bash: ./scripts/automation/shared_services-cd.sh 
          workingDirectory: .
          displayName: 'Deploy TF Backend'
          env:
            ARM_CLIENT_ID: $(AzCreds.AZ_SPN)
            ARM_CLIENT_SECRET: $(AzCreds.AZ_SPN_KEY)
            ARM_SUBSCRIPTION_ID: $(AzCreds.AZ_SUB_ID)
            ARM_TENANT_ID: $(AzCreds.AZ_TENANT)
            TF_VAR_environment_id: $(ENVIRONMENT_ID)
            TF_VAR_location: $(LOCATION)
            TF_VAR_virtual_network_cidr: $(SUBNET_CIDR)
