resources:
  pipelines:
  - pipeline: boundary-ci
    source: BOUNDARY CI
    trigger:
      branches:
        - master

# TODO: Service connection not currently set via a variable due to this
# unresolved issue: https://github.com/microsoft/azure-pipelines-agent/issues/1307#issuecomment-403194600
variables:
  DOCKER_IMAGE: boundary-dev:latest
  DOCKER_REGISTRY_URL: bodev.azurecr.io

stages:
  - stage: CD
    jobs:

    - job: CD
      pool:
        vmImage: 'ubuntu-latest'
      container:
        image: $(DOCKER_IMAGE)
        endpoint: boundaryACR
      
      steps:
        - checkout: self
        - checkout: git://TBD # TODO: Set dynamically - vars not currently supported
          persistCredentials: true

        - task: AzureCLI@2
          name: AzCreds
          displayName: Get Azure Credentials
          inputs:
              azureSubscription: TBD
              scriptType: bash
              addSpnToEnvironment: true
              scriptLocation: inlineScript
              inlineScript: |
                echo '##vso[task.setvariable variable=AZ_SPN;isOutput=true]'$servicePrincipalId
                echo '##vso[task.setvariable variable=AZ_SPN_KEY;isOutput=true]'$servicePrincipalKey
                echo '##vso[task.setvariable variable=AZ_TENANT;isOutput=true]'$tenantId
                AZ_SUB_ID=`az account show -o tsv | awk '{ print $3 }'`
                echo '##vso[task.setvariable variable=AZ_SUB_ID;isOutput=true]'$AZ_SUB_ID

        - bash: $(Build.SourcesDirectory)/TBD
          workingDirectory: $(Build.SourcesDirectory)/terraform-azurerm-sec-analytics-platform-workload
          displayName: 'CD Script'
          env:
            TERRAFORM_AZURE_BACKEND_DIR_PATH: $(Build.SourcesDirectory)/TBD
            TERRAFORM_CONFIG_DIR_PATH: $(Build.SourcesDirectory)/TBD
            TERRAFORM_AZURE_BACKEND_LOCATION: uksouth
            TERRAFORM_AZURE_BACKEND_NAME_PREFIX: boundary
            ARM_CLIENT_ID: $(AzCreds.AZ_SPN)
            ARM_CLIENT_SECRET: $(AzCreds.AZ_SPN_KEY)
            ARM_SUBSCRIPTION_ID: $(AzCreds.AZ_SUB_ID)
            ARM_TENANT_ID: $(AzCreds.AZ_TENANT)
