stages:
  - stage: CI
    jobs:
    - template: templates/dockerCI.yml
      parameters:
        DOCKER_REGISTRY_SERVICE_CONNECTION: acr_connection
        DOCKER_REGISTRY_URL: acr${ENVIRONMENT_ID}.azurecr.io
    - template: templates/terraformCI.yml
      parameters:
        DOCKER_IMAGE: ssbuild-dev:latest
        DOCKER_REGISTRY_SERVICE_CONNECTION: acr_connection
      
