# TODO: Service connection not currently set via a variable due to this
# unresolved issue: https://github.com/microsoft/azure-pipelines-agent/issues/1307#issuecomment-403194600

stages:
  - stage: CI
    jobs:
    - template: templates/terraformCI.yml
      parameters:
        DOCKER_IMAGE: brightside-dev:latest
        DOCKER_REGISTRY_SERVICE_CONNECTION: brightsideACR
    - template: templates/dockerCI.yml
      parameters:
        DOCKER_REGISTRY_SERVICE_CONNECTION: brightsideACR
        DOCKER_REGISTRY_URL: brdev.azurecr.io
