variables:
- name: DOCKER_REGISTRY_SERVICE_CONNECTION
  value: acr_connection
- name: DOCKER_IMAGE_NAME
  value: ssbuild-dev

jobs:

- job: DockerCI

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: $(DOCKER_REGISTRY_SERVICE_CONNECTION)

  - bash: scripts/automation/docker-ci.sh
    displayName: 'Docker CI'
    env:
      DOCKER_REGISTRY_URL: acr$(ENVIRONMENT_ID).azurecr.io
      DOCKERFILE_PATH: ".devcontainer/Dockerfile"
      DOCKER_IMAGE_NAME: $(DOCKER_IMAGE_NAME)


- job: TerraformCI

  dependsOn: DockerCI

  pool:
    vmImage: 'ubuntu-latest'

  container:
    image: $(DOCKER_IMAGE)
    endpoint: $(DOCKER_REGISTRY_SERVICE_CONNECTION)

  steps:
  - task: AzureCLI@2
    name: AzCreds
    displayName: Get Azure Credentials
    inputs:
        azureSubscription: brightsideARM-tobe
        scriptType: bash
        addSpnToEnvironment: true
        scriptLocation: inlineScript
        inlineScript: |
          echo '##vso[task.setvariable variable=AZ_SPN;isOutput=true]'$servicePrincipalId
          echo '##vso[task.setvariable variable=AZ_SPN_KEY;isOutput=true]'$servicePrincipalKey
          echo '##vso[task.setvariable variable=AZ_TENANT;isOutput=true]'$tenantId
          AZ_SUB_ID=`az account show -o tsv | awk '{ print $3 }'`
          echo '##vso[task.setvariable variable=AZ_SUB_ID;isOutput=true]'$AZ_SUB_ID


  - bash: ./scripts/automation/shared_services-ci.sh
    workingDirectory: .
    displayName: 'Terraform CI'
    env: 
      ARM_CLIENT_ID: $(AzCreds.AZ_SPN)
      ARM_CLIENT_SECRET: $(AzCreds.AZ_SPN_KEY)
      ARM_SUBSCRIPTION_ID: $(AzCreds.AZ_SUB_ID)
      ARM_TENANT_ID: $(AzCreds.AZ_TENANT)
      TF_VAR_virtual_network_cidr: $(SHARED_VNET_CIDR)
      TF_VAR_location: $(LOCATION)
